config/routes.rb
Rails.application.routes.draw do
  resources :postes
  resources :bairros
  resources :cidades
  resources :users do
    collection do
      get 'perfil', to: 'users#perfil'
      patch 'update_password', to: 'users#update_password'
    end
  end
  resources :auth
  resources :perfil
  # Defines the root path route ("/")
  post 'login', to: 'auth#login'
  root "home#index"
end

app/models/poste.rb
class Poste < ApplicationRecord
  belongs_to :user, foreign_key: 'users_id'
  has_one_attached :file
  belongs_to :cidade
  belongs_to :bairro
end

app/controllers/postes_controller.rb
class PostesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: %i[create update destroy]
  
  # Exige autenticação apenas para `json` e `xlsx` no endpoint `index`
  before_action :authorized_user, only: %i[show create update destroy], if: -> { request.format.json? || request.format.xlsx? }
  before_action :authorized_user, only: %i[index], if: -> { request.format.json? || request.format.xlsx? }
  before_action :set_poste, only: %i[show edit update destroy]

  # GET /postes or /postes.json
def index
  @postes = Poste.includes(:bairro, :cidade).page(params[:page]).per(6) # 10 registros por página

  respond_to do |format|
    format.html # Renderiza o arquivo index.html.erb normalmente
    format.xlsx
    format.json do
      render json: {
        postes: @postes.map do |poste|
          {
            id: poste.id,
            users_id: poste.users_id,
            zonautm: poste.zonautm,
            localizacao_utm_x: poste.localizacao_utm_x,
            localizacao_utm_y: poste.localizacao_utm_y,
            observacoes: poste.observacoes,
            data_registro: poste.data_registro,
            created_at: poste.created_at,
            updated_at: poste.updated_at,
            file_url: poste.file.attached? ? url_for(poste.file) : nil,
            bairro: {
              id: poste.bairro.id,
              nome: poste.bairro.nome
            },
            cidade: {
              id: poste.cidade.id,
              nome: poste.cidade.nome
            }
          }
        end,
        pagination: {
          current_page: @postes.current_page,
          total_pages: @postes.total_pages,
          total_count: @postes.total_count
        }
      }
    end
  end
end

  

  # GET /postes/1 or /postes/1.json
  def show
    respond_to do |format|
      format.html # Renderiza a view padrão
      format.json do
        render json: {
          id: @poste.id,
          users_id: @poste.users_id,
          zonautm: @poste.zonautm,
          localizacao_utm_x: @poste.localizacao_utm_x,
          localizacao_utm_y: @poste.localizacao_utm_y,
          observacoes: @poste.observacoes,
          data_registro: @poste.data_registro,
          created_at: @poste.created_at,
          updated_at: @poste.updated_at,
          file_url: url_for(@poste.file),
          bairro: {
            id: @poste.bairro.id,
            nome: @poste.bairro.nome
          },
          cidade: {
            id: @poste.cidade.id,
            nome: @poste.cidade.nome
          }
        }
      end
    end
  end   

  # GET /postes/new
  def new
    @poste = Poste.new
  end

  # GET /postes/1/edit
  def edit
  end

  # POST /postes or /postes.json
  def create
    @poste = Poste.new(poste_params)
    @poste.users_id = @current_user.id # Usa o ID do usuário autenticado

    respond_to do |format|
      if @poste.save
        format.html { redirect_to @poste, notice: "Poste was successfully created." }
        format.json { render :show, status: :created, location: @poste }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @poste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postes/1 or /postes/1.json
  def update
    respond_to do |format|
      if @poste.update(poste_params)
        format.html { redirect_to @poste, notice: "Poste was successfully updated." }
        format.json { render :show, status: :ok, location: @poste }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @poste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postes/1 or /postes/1.json
  def destroy
    @poste.destroy!

    respond_to do |format|
      format.html { redirect_to postes_path, status: :see_other, notice: "Poste was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poste
      @poste = Poste.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def poste_params
      params.require(:poste).permit(:users_id, :cidade_id, :bairro_id, :zonautm, :localizacao_utm_x, :localizacao_utm_y, :observacoes, :data_registro, :file)
    end
    
end

app/helpers/postes_helper.rb
module PostesHelper
end

app/views/postes/_form.html.erb
<%= form_with(model: poste) do |form| %>
  <% if poste.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(poste.errors.count, "error") %> prohibited this poste from being saved:</h2>

      <ul>
        <% poste.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :users_id %>
    <%= form.collection_select :users_id, User.all, :id, :username %>
  </div>

  <div>
    <%= form.label :file_path, style: "display: block" %>
    <%= form.text_field :file_path %>
  </div>

  <div class="field">
    <%= form.label :file, "Upload Foto" %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= form.label :cidade_id, style: "display: block" %>
    <%= form.text_field :cidade_id %>
  </div>

  <div>
    <%= form.label :bairro_id, style: "display: block" %>
    <%= form.text_field :bairro_id %>
  </div>

  <div>
    <%= form.label :zonautm, style: "display: block" %>
    <%= form.text_field :zonautm %>
  </div>

  <div>
    <%= form.label :localizacao_utm_x, style: "display: block" %>
    <%= form.text_field :localizacao_utm_x %>
  </div>

  <div>
    <%= form.label :localizacao_utm_y, style: "display: block" %>
    <%= form.text_field :localizacao_utm_y %>
  </div>

  <div>
    <%= form.label :observacoes, style: "display: block" %>
    <%= form.text_area :observacoes %>
  </div>

  <div>
    <%= form.label :data_registro, style: "display: block" %>
    <%= form.datetime_field :data_registro %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/postes/_poste.html.erb
<div id="<%= dom_id poste %>">
  <p>
    <strong>Users:</strong>
    <%= poste.users_id %>
  </p>

  <p>
    <strong>Foto:</strong>
    <%= poste.file %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= poste.cidade_id %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= poste.bairro_id %>
  </p>

  <p>
    <strong>Zonautm:</strong>
    <%= poste.zonautm %>
  </p>

  <p>
    <strong>Localizacao utm x:</strong>
    <%= poste.localizacao_utm_x %>
  </p>

  <p>
    <strong>Localizacao utm y:</strong>
    <%= poste.localizacao_utm_y %>
  </p>

  <p>
    <strong>Observacoes:</strong>
    <%= poste.observacoes %>
  </p>

  <p>
    <strong>Data registro:</strong>
    <%= poste.data_registro %>
  </p>

</div>

app/views/postes/edit.html.erb
<h1>Editing poste</h1>

<%= render "form", poste: @poste %>

<br>

<div>
  <%= link_to "Show this poste", @poste %> |
  <%= link_to "Back to postes", postes_path %>
</div>

app/views/postes/index.html.erb
<div data-controller="postes"></div>

app/views/postes/new.html.erb
<h1>New poste</h1>

<%= render "form", poste: @poste %>

<br>

<div>
  <%= link_to "Back to postes", postes_path %>
</div>

app/views/postes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @poste %>

<div>
  <%= link_to "Edit this poste", edit_poste_path(@poste) %> |
  <%= link_to "Back to postes", postes_path %>

  <% if @poste.file.attached? %>
  <%= image_tag url_for(@poste.file) %>
<% else %>
  <p>No image uploaded.</p>
<% end %>

  <%= button_to "Destroy this poste", @poste, method: :delete, data: { confirm: "Are you sure?" } %>
</div>