config/routes.rb
Rails.application.routes.draw do
  resources :postes
  resources :bairros
  resources :cidades
  resources :users do
    collection do
      get 'perfil', to: 'users#perfil'
      patch 'update_password', to: 'users#update_password'
    end
  end
  resources :auth
  resources :perfil
  # Defines the root path route ("/")
  post 'login', to: 'auth#login'
  root "home#index"
end

app/models/bairro.rb
class Bairro < ApplicationRecord
  has_many :postes
end

app/controllers/bairros_controller.rb
class BairrosController < ApplicationController
  before_action :set_bairro, only: %i[ show edit update destroy ]
  before_action :authorized_user, only: %i[show create update destroy], if: -> { request.format.json?  }
  before_action :authorized_user, only: %i[index], if: -> { request.format.json?  }

  # GET /bairros or /bairros.json
  def index
    if params[:cidade_id].present?
      @bairros = Bairro.where(cidade_id: params[:cidade_id])
    else
      @bairros = Bairro.all
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bairros }
    end
  end

  # GET /bairros/1 or /bairros/1.json
  def show
  end

  # GET /bairros/new
  def new
    @bairro = Bairro.new
  end

  # GET /bairros/1/edit
  def edit
  end

  # POST /bairros or /bairros.json
  def create
    @bairro = Bairro.new(bairro_params)

    respond_to do |format|
      if @bairro.save
        format.html { redirect_to @bairro, notice: "Bairro was successfully created." }
        format.json { render :show, status: :created, location: @bairro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bairro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bairros/1 or /bairros/1.json
  def update
    respond_to do |format|
      if @bairro.update(bairro_params)
        format.html { redirect_to @bairro, notice: "Bairro was successfully updated." }
        format.json { render :show, status: :ok, location: @bairro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bairro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bairros/1 or /bairros/1.json
  def destroy
    @bairro.destroy!

    respond_to do |format|
      format.html { redirect_to bairros_path, status: :see_other, notice: "Bairro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bairro
      @bairro = Bairro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bairro_params
      params.require(:bairro).permit(:nome, :cidade_id)
    end
end

app/helpers/bairros_helper.rb
module BairrosHelper
end

app/views/bairros/_bairro.html.erb
<div id="<%= dom_id bairro %>">
  <p>
    <strong>Nome:</strong>
    <%= bairro.nome %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= bairro.cidade_id %>
  </p>

</div>

app/views/bairros/_form.html.erb
<%= form_with(model: bairro) do |form| %>
  <% if bairro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bairro.errors.count, "error") %> prohibited this bairro from being saved:</h2>

      <ul>
        <% bairro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cidade_id, style: "display: block" %>
    <%= form.text_field :cidade_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bairros/edit.html.erb
<h1>Editing bairro</h1>

<%= render "form", bairro: @bairro %>

<br>

<div>
  <%= link_to "Show this bairro", @bairro %> |
  <%= link_to "Back to bairros", bairros_path %>
</div>

app/views/bairros/index.html.erb
<div class="w-full h-screen flex flex-col gap-14 px-24">
  <p class="text-green-500"><%= notice %></p>
  <h1 class="text-4xl font-bold text-blue-600">Bairros</h1>
  <%= link_to "Nova Bairro", new_bairro_path, class: "bg-blue-500 text-white p-3 rounded-lg hover:bg-blue-600 transition-colors duration-200 w-40 text-center" %>
  

  <div id="bairros" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8 w-full px-10">
    <% @bairros.each do |bairro| %>
      <div class="bg-white shadow-md rounded-lg p-6 hover:shadow-lg transition-shadow duration-300">
        <h2 class="text-xl font-semibold text-gray-800"><%= bairro.nome %></h2>
        <p class="text-sm text-gray-600 mb-4">Group: <%= bairro.cidade_id %></p>
        
        <%= link_to "Ver bairro", bairro, class: "text-indigo-600 hover:underline font-medium" %>
      </div>
    <% end %>
  </div>

</div>

app/views/bairros/new.html.erb
<h1>New bairro</h1>

<%= render "form", bairro: @bairro %>

<br>

<div>
  <%= link_to "Back to bairros", bairros_path %>
</div>

app/views/bairros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bairro %>

<div>
  <%= link_to "Edit this bairro", edit_bairro_path(@bairro) %> |
  <%= link_to "Back to bairros", bairros_path %>

  <%= button_to "Destroy this bairro", @bairro, method: :delete %>
</div>